[en]
languageName = "English"
languageDirection = "ltr"
# contentDir = "content/en"
title = "HeavenGospal's blog"
weight = 2

[en.params]
sidebar.subtitle = "Programming, Algorithms, Chit-chat..."
article.license.default = "Licensed under CC BY-NC-SA 4.0"

[zh-cn]
languageName = "简体中文"
languageDirection = "ltr"
# contentDir = "content/zh-cn"
title = "天国福音的博客"
weight = 1

[zh-cn.params]
sidebar.subtitle = "编程、算法、闲聊..."
article.license.default = "使用 CC BY-NC-SA 4.0 协议"